### ISSUE TITLE
Header covering list view

### ISSUE THREAD

**Issue by ieee-matthew-butler** [virtualprodigy/Alphabet-Scrolling-List#2]
I installed the library and I can see that the search bar is covering the list view. Please see the screenshot.
![screen shot 2017-12-01 at 2 51 35 pm](https://user-images.githubusercontent.com/34171295/33500552-2fa5e272-d6a7-11e7-85cf-650422438d64.png)

**Comment by virtualprodigy** [comment]
fix implemented. will be in the next release
